#!/bin/bash

# Perform any final installations and setups before running tests on Travis
cd cadasta/core
npm install bootstrap-sass
cd ..
./manage.py migrate
./manage.py loadstatic
./manage.py loadfunctestfixtures
./manage.py runserver 0.0.0.0:8000 &
sleep 5  # Wait for the Django server to start up
cd ..

export CADASTA_TEST_WEBDRIVER=Firefox
./runtests.py --functional
ret=$?

killall python  # Kill the Django server
exit $ret
